import type { AppStatus } from '@/entities/app';

export const ApiRoutes = {
	LOGIN: 'auth/login',
	GET_MY_INFO: 'user/info',
	GET_ALL_LANGUAGES: 'apps/languages',
	TRANSLATE_TEXT: 'deepl/translate',
	UPLOAD_IMAGE: 'file/image',
	UPLOAD_MODFILE: 'file/modfile',
	CREATE_APP: 'apps',
	GET_ALL_APPS: 'apps',
	EDIT_APP: (id: number): string => `apps/${id}`,
	GET_APP_BY_ID: (id: number): string => `apps/${id}`,
	DELETE_APP: (id: number): string => `apps/${id}`,
	SET_APP_STATUS: (appId: number, status: AppStatus): string => `apps/${appId}/status/${status}`,
	UPLOAD_SCREENSHOTS: (appId: number): string => `apps/${appId}/screenshots`,
	UPLOAD_APK: (appId: number): string => `apps/${appId}/apk`,
	UPLOAD_BUNDLE: (appId: number): string => `apps/${appId}/bundle`,
	UPLOAD_APP_FIREBASE: (appId: number): string => `apps/${appId}/firebase`,
	GET_ISSUES_COUNTS: (appId: number): string => `apps/${appId}/issue/counts`,
	GET_ALL_APP_ISSUES: (appId: number): string => `apps/${appId}/issue`,
	SET_APP_ORDER: 'apps/order/set',
	SET_APP_MODS_ORDER: (appId: number): string => `apps/${appId}/mod/order/set`,
	SEARCH_APP_MODS: (appId: number, isActived: boolean): string => `apps/${appId}/mod/${isActived ? 'actived' : 'inactived'}`,
	DELETE_APP_ISSUE: (appId: number, issueId: number): string => `apps/${appId}/issue/${issueId}/delete`,
	SOLVE_APP_ISSUE: (appId: number, issueId: number): string => `apps/${appId}/issue/${issueId}/solve`,
	TOGGLE_APP_MOD: (appId: number, modId: number): string => `apps/${appId}/mod/${modId}/toggle`,
	TOGGLE_ADS_VISIBILITY: (appId: number): string => `apps/${appId}/sdk/ads/toggle`,
	UPDATE_SDK: (appId: number): string => `apps/${appId}/sdk`,
	CREATE_MOD: `mod`,
	CREATE_POLICY: `policy`,
	DELETE_POLICY: (slug: string): string => `policy/${slug}`,
	GET_POLICY_BY_SLUG: (slug: string): string => `policy/${slug}`,
	EDIT_POLICY: (slug: string): string => `policy/${slug}`,
	GET_ALL_POLICIES: `policy`,
	EDIT_MOD: (id: number): string => `mod/${id}`,
	GET_MOD_BY_ID: (modId): string => `mod/${modId}`,
	DELETE_MOD_BY_ID: (modId): string => `mod/${modId}`,
	SEARCH_MODS: `mod/search`,
	GET_ALL_MODS_VERSIONS: `mod/versions`
} satisfies Record<string, string | ((...args: any[]) => string)>;
